name: "web3"
mode: "dev"
port: 80
version: "v0.0.1"
start_time: "2022-08-26"
machine_id: 1
Bsc:
  Name: "Bsc"
  Url: "https://bsc-dataseed3.defibit.io"
  ChainId: "56"
  Symbol: "BNB"
auth:
  jwt_expire: 8760 #JWT过期时间
log:
  level: "debug"
  filename: "web3.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns: 2000
  max_idle_conns: 100
redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100